from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os

class PDFGenerator:
    # Removed filename from __init__ as it's now dynamically set in build
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.story = []

    def add_title(self, title):
        self.story.append(Paragraph(title, self.styles["Title"]))
        self.story.append(Spacer(1, 12))

    def add_heading(self, text, level=1):
        if level == 1:
            self.story.append(Paragraph(text, self.styles["h1"]))
        elif level == 2:
            self.story.append(Paragraph(text, self.styles["h2"]))
        else:
            self.story.append(Paragraph(text, self.styles["h3"]))
        self.story.append(Spacer(1, 6))

    def add_paragraph(self, text):
        self.story.append(Paragraph(text, self.styles["BodyText"]))
        self.story.append(Spacer(1, 12))

    # Build method now takes original_text, analysis_result, and output_dir
    def build(self, original_text: str, analysis_result: dict, output_dir: str = "reports"):
        # Clear story for each new report generated by this instance
        self.story = [] 

        os.makedirs(output_dir, exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        # Sanitize filename part from original text
        safe_filename_part = original_text[:50].replace(" ", "_").replace(".", "").replace(",", "").replace("/", "").replace("\\", "").replace(":", "") 
        pdf_filename = os.path.join(output_dir, f"report_{safe_filename_part}_{timestamp}.pdf")
        
        # Initialize SimpleDocTemplate here, just before building
        doc = SimpleDocTemplate(pdf_filename, pagesize=letter) 

        self.add_title("Document Analysis Report")
        self.add_paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        self.story.append(Spacer(1, 24))

        self.add_heading("Original Document Snippet:", level=2)
        display_text = original_text if len(original_text) < 500 else original_text[:500] + "..."
        self.add_paragraph(f"\" {display_text} \"")
        self.story.append(Spacer(1, 18))

        self.add_heading("Analysis Results:", level=2)
        
        sentiment_label = analysis_result['sentiment']
        if sentiment_label == 'POSITIVE':
            sentiment_display = f"<font color='green'><b>{sentiment_label}</b></font>"
        elif sentiment_label == 'NEGATIVE':
            sentiment_display = f"<font color='red'><b>{sentiment_label}</b></font>"
        else: # NEUTRAL
            sentiment_display = f"<font color='blue'><b>{sentiment_label}</b></font>"

        self.add_paragraph(f"• Sentiment: {sentiment_display} (Confidence: {analysis_result['confidence']:.2f})")
        self.add_paragraph(f"• Summary: {analysis_result['summary']}")
        self.story.append(Spacer(1, 24))

        print(f"Generating PDF report: {pdf_filename}")
        doc.build(self.story) # Build using the local 'doc' variable
        print("PDF report generated successfully.")

if __name__ == "__main__":
    sample_result = {
        "sentiment": "POSITIVE",
        "confidence": 0.99,
        "summary": "The product was amazing and exceeded expectations."
    }
    sample_original_text = "This is the original text that was analyzed. The product was amazing and exceeded expectations."
    pdf = PDFGenerator() # No filename needed here
    pdf.build(sample_original_text, sample_result, output_dir="sample_reports") # Specify output_dir for example